appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: xYFjCuX8IjBtKgmrkhjj/Tep+rDBpbtAJELV2RIHxjFp4rxrIsp7mQf5XQjwOyUJjFa4Cw9cQ2r84r+ETkk88j/7SmJehW3QzaUMCwf3yf7PzDr52kShfSRJa2go6qbWtnSiQBTyTudxUe6qhZPDTCrL82P/QDTamZi+XFAOZKx6qzu/Xdcny7Tau6WW2Ce/WmqJim4s1QCx+q+ox6CNPaI0A+N1tutEoeTiMV8hCK5JUwONXY2/SIAAVyYc5OU+ACK+HdsG+OxI2ncL3If9XsuTJ81vluljXvtWfW2N0Ze3+a02eBFvft8akvmbbH5VSdAIb4Fr17PRrMZKRMB4SrywVe7zPWSFpQ4d9TGUMpBPJ9xEu5sWGKkpY5qJV/Kxf5TO3Kd1BUpRFvXFua2HDr4H7PVPMOJcijx7n3n+aPyFw8YDFgzHWvrjAPvxAKfCu8CaRXEOzr5qfyS/cjBX+KJw8WxHb03hHPXq6R0U1DILVLJ0oy5QIkFdNER7NyonzfxFw1/Xm+/oIP6z1k/tZ6Pmix1Tdao0YVdkv9D0qmSA/KW9lEm1NaVzgyvzOCbTquQISlaP4x9OI7VsO7+NSNuPa2QX9f8cgJu39P2EwKcDDtUcnsJ/N9yaQJVkcNUaZxQaHjfSRdHD0XCchFo+XYJipmaBABiDNDyA7Y2v018=
